---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-local-pv-provisioner
  namespace: kube-system

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: k8s-local-pv-provisioner
rules:
  - apiGroups:
      - ""
    resources:
      - persistentvolumes
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: k8s-local-pv-provisioner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-local-pv-provisioner
subjects:
  - kind: ServiceAccount
    name: k8s-local-pv-provisioner
    namespace: kube-system
